#version: '2'
#
#services:
#  app:
#    build:
#      context: .
#    image: 'docker-spring-boot-postgres:latest'
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/BookService
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=12345
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network
#
#  db:
#    image: 'postgres:13.1-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_DB=BookService
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=12345
#    ports:
#      - "5432:5432"
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge
version: "3.9"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=BookService
    ports:
      - '5432:5432'
    networks:
      - recipe-app

  recipe:
    container_name: recipe_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/BookService
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
    networks:
      - recipe-app

networks:
  recipe-app:
    driver: bridge
